### ISSUE TITLE
 github-actions[bot] spam issue 

### ISSUE THREAD

**Issue by dr-nefardio3058** [jge162/Action-workflows#464]
### Hi Jeremy and Geo 👋 ,

_First of all, I wanted to let you know that I really like the ideas of workflows and bots to greet users on their first pull request and so on._

**The reason why I open this issue is that the bot sends too many messages to the email of the person who suggest pull request or issues: It's not a problem for a person who contributes little; but I have already opened 4 PR's and some issues and the bot send me like 3 emails for each PR/Issue, and 1+ email for each comment in these actions; basically it's a very annoying spam.**

What I suggest to solve this problem is squashing the mails so that instead of 3 mails ("Assigned #463 to @dr-nefardio3058", "Thank you for opening this issue! Our team will review it as soon as we can", Welcome to the REPO, This is your first time Opening an Issue!, etc.) , or setting a limit for "github-actions" to stop sending mails after "x" number of PR/ISSUES.

**Example** _(this +2 mails for an Issue and a PR)_:

![image](https://user-images.githubusercontent.com/124001513/222906961-99352752-b202-4d97-8d21-fbdc2c5af68d.png)

**My email inbox now:** _(just did some PR's in this repo. "That's a lot")_

![Screenshot_20230304_132241_Gmail](https://user-images.githubusercontent.com/124001513/222917319-616603fd-0496-447b-bdaf-d3a1d74dea8a.jpg)

That's all guys, see you. 👍

**Comment by dr-nefardio3058** [comment]
For example, I recieved 2 mails (from github-actions [assigned... , and thank you for..., basically all the messages in this thread) for opening this issue

**Comment by jge162** [comment]
Understood,  I will work on cleaning it up thanks.
