### ISSUE TITLE
version = release?

### ISSUE THREAD

**Issue by dr-nefardio3058** [jge162/Action-workflows#565]
### Hi Jeremy 👋 ,

**Browsing the readme I found this buttons for "version" and "release".**

Is this accuarate? Is version a different thing from release? **Shouldn't be better to delete version as release is more important?**

![image](https://user-images.githubusercontent.com/124001513/223872626-1b4cea3f-3e9d-4a62-95c4-c790d0605de4.png)

> Cya 🐱

**Comment by jge162** [comment]
version is for json; release is for current release.
